
SELECT
  RIGHT(LEFT(@@VERSION,25), 4) [PRODUCT_VERSION_NUMBER] , 
  SERVERPROPERTY('ProductVersion') [PRODUCT_VERSION],
  SERVERPROPERTY('ProductLevel') [PRODUCT_LEVEL],
  SERVERPROPERTY('Edition') [PRODUCT_EDITION],
  DATABASEPROPERTYEX('master', 'Version') [PRODUCT_NUMBER],
  @@VERSION [VERSION],
  @@SERVERNAME [SERVER_NAME],
  @@SERVICENAME [SERVICE_NAME]
